FROM arm32v7/python:3.7-slim-bullseye

WORKDIR /app

#ADD ./1033.png .

COPY requirements.txt ./

#RUN apt update && apt install -y libjpeg62-turbo libopenjp2-7 libtiff5 libatlas-base-dev libgl1-mesa-glx
RUN pip install -r requirements.txt
#RUN pip install pillow --index-url 'https://www.piwheels.org/simple'

COPY . .

CMD [ "python3", "-u", "./main.py" ]